-- This file is intentionally left empty.
-- The public.handle_new_user() function and trigger are already defined in 20250625000000_create_profiles_table.sql.
-- This file previously caused conflicts by attempting to redefine them.